### ISSUE TITLE
Set up a project that can be installed with npm

### ISSUE THREAD

**Issue by jeremiak** [18F/crime-data-style#1]
This pattern library will be used by front end applications, so it should be installable through NPM. It need not be published to the registry to satisfy this card. Just having a proper `package.json` and some project scaffolding will suffice for this issue

**Comment by jeremiak** [comment]
We will want to start earnest work on the style guide after this sprint, so that we have some components and styles to refactor out instead of doing a lot of work up front to keep two repos/release processes in sync. I am removing it from the epic

**Comment by LarryBafundo** [comment]
@jeremiak: do we want to pull this issue out of the current sprint and keep it in the backlog for later?

**Comment by jeremiak** [comment]
@LarryBafundo Yup! We aren't totally sure about how we're going to use `18f/crime-data-style` yet so let's move this out of the current sprint
