### ISSUE TITLE
The description for national reporting type is misleading 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/crime-data-style#3]
When a user queries data at the national level we currently say "the US reports summary data..." 

We should probably say that it reports both SRS & NIBRS.

**Comment by jeremiak** [comment]
I find that language to be a bit confusing because, technically, the US government as an entity doesn't submit data to the FBI for the nation

**Comment by harrisj** [comment]
Yes, it really should be something about "national totals" or nationwide reporting

**Comment by LarryBafundo** [comment]
lower priority for now, but thoughts @nicoleslaw?

**Comment by nicoleslaw** [comment]
I know we have a map of this, but do we have a data-informed / dynamic way to say something like:

> X states report SRS; X states report a mix of SRS and NIBRS; and X states only report NIBRS.

**Comment by jeremiak** [comment]
Yup, we do [have a data source](https://github.com/18F/crime-data-explorer/blob/master/data/ucr-program-participation.json) for that information and could generate that sentence.

**Comment by harrisj** [comment]
We could also derive from the database, but I would want to check with you on how we represent that. For instance, technically Illinois is a "hybrid" state that reports both SRS and NIBRS, but only a single agency in all of Illinois (Rockport, IL) reports NIBRS at the moment

**Comment by nicoleslaw** [comment]
Issue moved to [18F/crime-data-explorer #423](https://github.com/18F/crime-data-explorer/issues/423) via [**ZenHub**](https://www.zenhub.com/)
